### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by soyguijarro** [Karumi/learnyougit#5]
I wanted to try this since it looks seriously awesome, but the installation failed :disappointed: This is what I get when running `sudo npm install learnyougit -g`. I'm using Ubuntu 16.04, Node 6.9.1 and Npm 3.10.8.

```
/usr/bin/learnyougit -> /usr/lib/node_modules/learnyougit/learnyougit.js

> nodegit@0.16.0 install /usr/lib/node_modules/learnyougit/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl
/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl' }
/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl
/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl' }
/usr/lib
└── (empty)

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "learnyougit"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.
```

**Comment by Serchinastico** [comment]
First of all, thanks for reporting, @soyguijarro !

I'm seeing this is an issue while installing `nodegit` because it has a dependency on libssl. Here is the very same issue from not that long ago: https://github.com/nodegit/nodegit/issues/1134

Let us know if this solves your installation problems.

**Comment by soyguijarro** [comment]
Installing `libssl-dev` as instructed in that issue solved it :tada: Thanks a lot, @Serchinastico!

**Comment by RuiMiguel** [comment]
It fails me on my MacOS Sierra with node v4.5 and npm 2.15.9

$ npm install learnyougit -g

nodegit@0.16.0 install /usr/local/lib/node_modules/learnyougit/node_modules/nodegit
node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Configuring libssh2.
{ [Error: Command failed: /bin/sh -c /usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl' }
/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ [Error: Command failed: /bin/sh -c /usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "learnyougit" "-g"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rui.alonso/dev/node/npm-debug.log

**Comment by Serchinastico** [comment]
@RuiMiguel Have you tried with the solution posted above? (https://github.com/nodegit/nodegit/issues/1134)

**Comment by RuiMiguel** [comment]
Sorry, I've just seen Ubuntu on it ;) I'm installing now xcode-select as post says. 
It takes 40min to download, I told you later. Thanks!

**Comment by RuiMiguel** [comment]
ok @Serchinastico that work for mac too. I will try learnyougit with my team. Gracias :D

**Comment by Serchinastico** [comment]
Thanks to you for reporting 😄

**Comment by RamaDL** [comment]
On docker running Ubuntu I get this issue

root@2df571415161:/# npm install learnyougit -g
npm WARN deprecated colors-tmpl@0.1.1: no longer maintained
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
/usr/local/bin/learnyougit -> /usr/local/lib/node_modules/learnyougit/learnyougit.js

> nodegit@0.16.0 install /usr/local/lib/node_modules/learnyougit/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
node-pre-gyp ERR!
Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
gyp
WARN
EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.10.0"
gyp WARN
EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build'
make: *** No rule to make target '../.node-gyp/8.10.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build'
gyp

ERR! build error
gyp
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/learnyougit/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.87-linuxkit-aufs
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/learnyougit/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build/Release"
gyp ERR! cwd /usr/local/lib/node_modules/learnyougit/node_modules/nodegit
gyp
ERR! node -v v8.10.0
gyp
ERR! node-gyp -v v3.7.0
gyp ERR!
not ok
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/learnyougit/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/learnyougit/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.9.87-linuxkit-aufs
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/learnyougit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/learnyougit/node_modules/nodegit
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/learnyougit/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/learnyougit/node_modules/nodegit/build/Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
/usr/local/lib
`-- (empty)

npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "learnyougit" "-g"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1

**Comment by RamaDL** [comment]
Linux solution (on Mac OS same steps from the second step)
Solved! learnyougit do not work with newest versions of nodejs and nom, so we need to do a downgrade of node. 
**Steps:**
1º - Install the latest stable version of nodejs and nom:
    `$ apt install nodes && apt install npm`
2º - Install n
    `$ npm i -g n`               # Install n globally
3º - Install with n the versión 5.11.1 of nodejs
    `$ n latest`                 # Install latest version of node 
    `$ n ls`                        # List all versions available
    `$ n 5.11.1`                  # Install and switch to an earlier version
4º - Install learnyougit with downgraded version of nom
    `PATH_TO_THE_DOWNGRADED_NODE_VERSION/bin/npm i -g learnyougit`

Enjoy it!!!

**Comment by Serchinastico** [comment]
I will take care of updating the repository when I found some time to address the issue, in the meantime PRs are more than welcome.
